exclude: "docs|node_modules|migrations|.git|.venv"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: check for uncreated migrations.
        entry: .venv/bin/python ./manage.py makemigrations --check --dry-run
        types: ["python"]
        pass_filenames: false
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]
  - repo: local
    hooks:
      - id: tests
        language: system
        name: run tests
        entry: .venv/bin/python ./manage.py test
        types: ["python"]
        pass_filenames: false
        stages: ["push"]
