version: '3'

volumes:
  ayushma_local_postgres_data: {}
  ayushma_local_postgres_data_backups: {}
  ayushma_local_milvus_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: ayushma_local
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
    networks:
      - default

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ayushma_postgres
    volumes:
      - ayushma_local_postgres_data:/var/lib/postgresql/data:Z
      - ayushma_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - default

  redis:
    image: redis:6
    networks:
      - default

  celeryworker:
    <<: *django
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    ports: []
    command: /start-celerybeat

  milvus:
    image: milvusdb/milvus:v2.4.5
    container_name: milvus-standalone
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
      - COMMON_STORAGETYPE=local
    volumes:
      - ayushma_local_milvus_data:/var/lib/milvus
      - ./compose/production/milvus/embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    networks:
      - default

networks:
  default:
    name: ayushma_local
